AllCops:
  DisplayCopNames: true

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/LineLength:
  IgnoredPatterns:
    - !ruby/regexp /^\s*#/

Metrics/MethodLength:
  Exclude:
    - test/**/*

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/NegatedIf:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
