inherit_gem:
  the_bath_of_zahn: config/rubocop.yml

AllCops:
  DisplayCopNames: true

Style/WhileUntilModifier:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"

Style/GlobalVars:
  Enabled: false
