[package]
name = "kkttyl"
version = "0.1.0"
authors = ["Zach Ahn <engineering@zachahn.com>"]

[lib]
name = "kkttyl"
crate-type = ["cdylib"]

[dependencies]
notify = "4.0.1"

[dev-dependencies]
tempdir = "^0.3.5"
