[package]
name = "kkttyl"
version = "0.0.4"
authors = ["Zach Ahn <engineering@zachahn.com>"]

[lib]
name = "kkttyl"
crate-type = ["cdylib"]

[dependencies]
notify = "4.0.1"
libc = "0.2.22"

[dev-dependencies]
tempdir = "^0.3.5"
